<div id="details" class="text-center align-middle">

    <div id="remodelar" tabindex='-1' class="container-fluid text-center collapse hidden-element padding-botton-1">
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
            <div class="col-lg-10 col-xs-10 col-md-10 details-box">
            	<h2>Si queres reformar o ampliar y no sabes como hacer?</h2>
            	<p>Contanos tu idea, que te gustaría hacer, y en conjunto nos ponemos a trabajar para
que la propiedad se transforme en lo que soñaste.
En este proceso optimizamos recursos y materiales logrando economía aprovechando
lo existente. Sumamos funcionalidad ,innovación y estética, partiendo como punto
base desde tus ideas y necesidades, hasta lograr un resultado óptimo.</p>
            	<div class="flex-container">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            	</div>
            	<p>Para saber cómo hacemos esto realidad, <a onclick="javascript:openModal();">hacé click acá donde te contamos de qué manera trabajamos.</a></p>
            </div>
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
    </div>
    
    <div id="construccion" tabindex='-1' class="container-fluid text-center collapse hidden-element padding-botton-1">
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
            <div class="col-lg-10 col-xs-10 col-md-10 details-box">
            	<h2>Queres hacer tu casa?</h2>
            	<p>Nosotros la construimos junto a vos!
Una casa es un proyecto de vida, es tu refugio, es un lugar donde vas a pasar gran
parte de tu vida, por eso es oportuno pensarla, planificarla y diseñarla con cuidado,
respetando los gustos, estilos, ideas, y usos de la familia.
En este proceso te podemos acompañar desde la elección del terreno, si es que aún no
lo tienes, contándote cuales son las ventajas y desventajas, pasando por el diseño y
distribución hasta la realización completa, con los materiales, colores y elementos que
imaginaste hasta concretar una idea deseada y construirla.</p>
            	<div class="flex-container">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            	</div>
            	<p>Para saber cómo hacemos esto realidad, <a onclick="javascript:openModal();">hacé click acá donde te contamos de qué manera trabajamos.</a></p>
            </div>
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
    </div>
    
    <div id="reformas" tabindex='-1' class="container-fluid text-center collapse hidden-element padding-botton-1">
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
            <div class="col-lg-10 col-xs-10 col-md-10 details-box">
            	<h2>Querés modernizar tu comercio, local o empresa?</h2>
            	<p>Contactanos y comenzamos a asesorarte para encontrar la imagen que buscas, ya sea
atraer a mas clientes o afianzar el vínculo con los de siempre.
Mejoramos tu imagen corporativa o comercial, ya sea mediante acciones simples o
contundentes que van desde la renovación y actualización de locales comerciales
(incluyendo iluminación, muebles, colores, fragancias, etc.) hasta el traslado a nuevas
instalaciones (trabajando también en la imágen corporativa: logos, estética,
vestimenta, uniformes, etc.)</p>
            	<div class="flex-container">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            	</div>
            	<p>Para saber cómo hacemos esto realidad, <a onclick="javascript:openModal();">hacé click acá donde te contamos de qué manera trabajamos.</a></p>
            </div>
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
    </div>
    
    <div id="comerciales" tabindex='-1' class="container-fluid text-center collapse hidden-element padding-botton-1">
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
            <div class="col-lg-10 col-xs-10 col-md-10 details-box">
            	<h2>Necesitas hacer una habilitación?</h2>
            	<p>Llamanos, nosotros la hacemos, tanto en provincia de BS AS, como en CABA. Hacemos
habilitaciones para carteles, marquesinas, locales, comercios minoristas, mayoristas,
industrias y servicios. Lo realizamos inspeccionando personalmente el lugar, a los fines
de verificar que el mismo reúna la totalidad de los requisitos urbanísticos y
constructivos exigidos en la normativa vigente.
Posteriormente confeccionamos la documentación técnica necesaria, que tendrá
carácter de declaración jurada, la cual, una vez suscripta por vos, será rubricada por el
Consejo Profesional respectivo.</p>
            	<div class="flex-container">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            	</div>
            </div>
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
    </div>
    
    <div id="planos" tabindex='-1' class="container-fluid text-center collapse hidden-element padding-botton-1">
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
            <div class="col-lg-10 col-xs-10 col-md-10 details-box">
            	<h2>Necesitas un plano municipal? Pero qué tipos de construcciones deben tener planos?</h2>
            	<p>Todas sin excepción. Si compraste una casa sin planos , o hiciste reformas internas, ampliaste
tu vivienda o solo la modificaste, o construiste una obra nueva sin ningún plano, Debes
regularizar la situación.
Nosotros te realizamos el plano y el trámite para regularizar la obra ejecutada sin permiso, ya
sea reglamentaria o antirreglamentaria. Contactanos!</p>
<h1>Ley 257 ?</h1>
<p>La Ley 257 de la Ciudad Autónoma de Buenos Aires establece las obligaciones del propietario
relativas a la conservación de su inmueble. El objetivo final del trámite es la obtención del
Certificado de Conservación. De acuerdo a la normativa vigente, todos los edificios, casas y PH,
deben mantener en buen estado de conservación de sus fachadas y sectores internos (huecos
de aire y luz). En donde sea posible el desprendimiento de elementos de mampostería,
estructurales, antenas, equipos de climatización, macetas, marquesinas, toldos, carteles, etc.,
que puedan ocasionar peligro para las personas o bienes.
 En qué consiste el trámite?
Elaboramos un Informe Técnico que se realiza a partir de la inspección visual de todos los
elementos descriptos, momento en el cual se toman muestras fotográficas, con el fin de
establecer la existencia o no de patologías. El Informe Técnico entonces, establece el estado de
prevención e integridad del inmueble.
A) Cuando el inmueble esté en buenas condiciones, se emitirá el Certificado de Conservación,
con una validez de acuerdo a la antigüedad del edificio, y que deberá renovarse una vez
vencido.
B) Si por el contrario presenta elementos deteriorados, se otorgará un plazo para efectuar las
reparaciones, vencido el cual se hará otra visita para constatar la situación y se realizará el
Certificado de Conservación en ese momento.
Que pasos seguimos para obtener el Certificado de Conservación :
A) Análisis del estado de frentes, contrafrentes, huecos de aire y luz y medianeras. Inspección,
relevamiento fotográfico.

B) Realización del Informe Técnico, firma del propietario y el arquitecto, presentación ante el
CPAU (Consejo de Profesionales de Arquitectura
y Urbanismo).
C) Entrega del Certificado de Conservación aprobado por la AGC (Agencia Gubernamental de
Control), dependencia del Gobierno
de la Ciudad.</p>
            	<div class="flex-container">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            	</div>
            </div>
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
    </div>
    
    <div id="recorridos" tabindex='-1' class="container-fluid text-center collapse hidden-element padding-botton-1">
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
            <div class="col-lg-10 col-xs-10 col-md-10 details-box">
            	<h2>Queres remodelar o ampliar tu casa???</h2>
            	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse semper porta nunc, eget venenatis elit varius eu. Nullam turpis erat, commodo id commodo a, venenatis sit amet lacus. Suspendisse quis vulputate felis, vitae gravida orci. Vivamus luctus velit nunc, sed viverra elit facilisis ac. Donec fermentum consequat leo. Mauris rhoncus tincidunt viverra. Nunc posuere libero augue. Maecenas imperdiet lacinia nisl, in convallis nunc sagittis non. Suspendisse interdum lectus ut metus suscipit, in commodo augue tincidunt.</p>
            	<div class="flex-container">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            		<img class="img-responsive flex-item" alt="" src="img/cocina.jpg">
            	</div>
            </div>
        <div class="col-lg-1 col-xs-1 col-md-1"></div>
    </div>


</div>