<div class="row">
    <div id="servicios" class="flex-container">
      <div onclick="javascript:openContainer('remodelar')" class="flex-item hover"><img src="img/reciclado.jpg" onmouseover="this.src='img/reciclado_o.jpg';" onmouseout="this.src='img/reciclado.jpg';" class="img-responsive" style="width:100%"></div>
      <div onclick="javascript:openContainer('construccion')" class="flex-item hover"><img src="img/construccion.jpg" onmouseover="this.src='img/construccion_o.jpg';" onmouseout="this.src='img/construccion.jpg';" class="img-responsive" style="width:100%"></div>
      <div onclick="javascript:openContainer('reformas')" class="flex-item hover"><img src="img/comerciales.jpg" onmouseover="this.src='img/comerciales_o.jpg';" onmouseout="this.src='img/comerciales.jpg';" class="img-responsive" style="width:100%"></div>  
      <div onclick="javascript:openContainer('comerciales')" class="flex-item hover"><img src="img/habcomer.jpg" onmouseover="this.src='img/habcomer_o.jpg';" onmouseout="this.src='img/habcomer.jpg';" class="img-responsive" style="width:100%"></div>
      <div onclick="javascript:openContainer('planos')" class="flex-item hover"><img src="img/planos.jpg" onmouseover="this.src='img/planos_o.jpg';" onmouseout="this.src='img/planos.jpg';" class="img-responsive" style="width:100%"></div>
      <div onclick="javascript:openContainer('recorridos')" class="flex-item hover"><img src="img/3d.jpg" onmouseover="this.src='img/3d_o.jpg';" onmouseout="this.src='img/3d.jpg';" class="img-responsive" style="width:100%"></div>  
    </div>
</div>


