<div class="row">
    <div class="flex-container">
      <div onclick="javascript:openContainer('remodelar')" class="flex-item"><?php include 'flex1.phtml';?></div>
      <div onclick="javascript:openContainer('construccion')" class="flex-item"><?php include 'flex2.phtml';?></div>
      <div onclick="javascript:openContainer('reformas')" class="flex-item"><?php include 'flex3.phtml';?></div>  
      <div onclick="javascript:openContainer('comerciales')" class="flex-item"><?php include 'flex4.phtml';?></div>
      <div onclick="javascript:openContainer('planos')" class="flex-item"><?php include 'flex5.phtml';?></div>
      <div onclick="javascript:openContainer('recorridos')" class="flex-item"><?php include 'flex6.phtml';?></div>  
    </div>
</div>


