<div id="footer" class="footer">
	<div class="flex-container">
		<div class="flex-item">
			<p>Lorem Ipsum is simply dummy text of the printing and typesetting
				industry. Lorem Ipsum has been the industry's standard dummy text
				ever since the 1500s, when an unknown printer took a galley of type
				and scrambled it to make a type specimen book. It has survived not
				only five centuries, but also the leap into electronic typesetting,
				remaining essentially unchanged. It was popularised in the 1960s
				with the release of Letraset sheets containing Lorem Ipsum passages,
				and more recently with desktop publishing software like Aldus
				PageMaker including versions of Lorem Ipsum.</p>
		</div>

		<div class="flex-item">
			<p>Buscanos en</p>
			<ul>
				<li><a href="#">Facebook</a></li>
				<li><a href="#">Pinterest</a></li>
				<li><a href="#">Instagram</a></li>
				<li><a href="#">LinkedIn</a></li>
			</ul>
		</div>

		<div class="flex-item">
			<h3>Contacto</h3>
			<form>
				<div class="form-group">
					<input type="text" name="name" placeholder="Nombre" /> <input
						type="text" name="email" placeholder="Email" /> <input type="text"
						name="title" placeholder="Titulo" />
					<textarea id="comment" placeholder="Consulta"></textarea>
					<input onclick="javascript:enviar();" type=button value="Enviar">
				</div>
			</form>
		</div>
	</div>
	<div class="sub-footer">
		<p>Copyright 2017 MR Arquitectura - Todos los derechos reservados.</p>
	</div>
</div>