<div class="footer">
	<div class="row">
    	<div class="col-lg-1 col-xs-1 col-md-1"></div>
    	
    		<div class="col-lg-6 col-xs-2 col-md-4"><p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. 
    		Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    		 It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
    		  It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
    		 and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p></div>
    	
    		<div class="col-lg-2 col-xs-2 col-md-2">
    			<ul>
    				<li>Buscanos en</li>
    				<li><a href="#">Facebook</a></li>
    				<li><a href="#">Pinterest</a></li>
    				<li><a href="#">Instagram</a></li>
    				<li><a href="#">LinkedIn</a></li>
    			</ul>
    		</div>
    	
    		<div class="col-lg-2 col-xs-2 col-md-2">
    			<h3>Contacto</h3>
    			<form>
    				<input type="text" name="name" placeholder="Nombre" />
    				<input type="text" name="email" placeholder="Email" />
    				<input type="text" name="title" placeholder="title" />
    				<textarea id="comment" placeholder="Consulta"></textarea>
    				<input onclick="javascript:enviar();" type=button value="Enviar" >
    			</form>
    		</div>
    	
    	<div class="col-lg-1 col-xs-1 col-md-1"></div>
	</div>
	<div class="row">
		<div class="sub-footer"><p>Copyright 2017 MR Arquitectura - Todos los derechos reservados.</p></div>
	</div>
	
</div>