<div class="modal-dialog">

	<!-- Modal content-->
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title">COMO TRABAJAMOS</h4>
		</div>
		<div class="modal-body">
			<h4>Primer Contacto</h4>
			<p>Nos contactamos, charlamos acerca de lo que estas necesitando y coordinamos un día para concretar el encuentro.
				Nos conocemos, nos contas cual es la idea que tenes y barremos temas que van desde miembros de la familia, usos y costumbres,
				ideas, imágenes, sueños, requisitos infaltables, gustos y demás elementos que nos sirvan para analizar con claridad cuál va a ser
				la mejor solución para ustedes. El tiempo aproximado de la visita es variable... con un café de por medio durará cerca de 2hs.</p>
			<h4>Croquis Preliminares + Anteproyecto</h4>
			<p>Implica realizar varias propuestas posibles, para que en un nuevo encuentro vos puedan analizar, modificar o combinar entre las distintas opciones que desarrollamos.
				Con estos cambios nosotros volvemos sobre los croquis, puliendo y armando el anteproyecto.Nos volvemos a encontrar por tercera vez donde te acercamos las propuestas
				 más ajustadas a tus gustos, y volvemos a corregirlo (ya que con seguridad comenzaste a imaginar al detalle los distintos espacios).
				  En la cuarta visita seguramente ya estaremos muy cerca del anteproyecto. En esta oportunidad afinaremos el lápiz y comenzaremos 
				  a charlar de temas más específicos (técnicos, estéticos, volumétricos. Con el croquis terminado veremos temas como estructura, techos, ventanas, 
				  calidades, terminaciones, revestimientos, calefacción, seguridad, estética, etc... y de esta manera alcanzamos el anteproyecto; el cual contara 
				  con Planos en planta, vistas, cortes y un presupuesto con plazos de obra aproximados.Una vez visto y revisado todo esto estamos en condiciones de realizar
				   el proyecto.</p>
			<h4>Proyecto</h4>
			<p>Aquí se desarrolla un trabajo estrictamente técnico (Planos, cortes, vistas, instalaciones sanitarias, eléctricas, TV, teléfono, etc...).
			Con esta documentación nos encontramos y verificamos si esta todo correcto, según tus requerimientos o sea si los enchufes están donde los precisas,
			 si la localización de ciertos caños están en un lugar que si en un futuro alguien tuviera que trabajar los encuentre correctamente, etc...
			 Una vez que terminamos estamos en condiciones de pedir cotizaciones a cada gremio o rubro que deberá intervenir en la concreción del proyecto.</p>
			<h4>Costos / Presupuesto de Obra</h4>
			<p>Tenemos 3 maneras de realizarlo:</p>
			<ul><li>La forma más rápida es tomar valores de referencia extraídos de nuestra experiencia, revistas y diarios especializados y tomar un valor por metro cuadrado. Lo que dará un valor estimado con un cierto margen de error bastante amplio.</li>
			<li>Otra manera de llegar a un valor más preciso es la cotización de cada gremio, rubro y proveedor interviniente en la obra, tomando como referencia aquellos con los que solemos trabajar cotidianamente.</li>
			<li>Otra forma es la combinación y comparación con rubros, gremios y proveedores que vos tengas y sean de tu confianza.</li></ul>
			<p>Aquí hay una tarea exclusiva del cliente (muy linda) donde nosotros te brindaremos todo nuestro apoyo conocimiento: te daremos un listado de elementos, 
			medidas y cantidades (revestimientos para pisos y paredes, cortinas, solias, artefactos de baño, griferías, muebles de cocina, etc...) 
			Con esto saldrán a pasear, ver y anotar los precios según sus gustos, pero aún no lo definimos ni compramos; mientras tanto nosotros nos encargamos
			 de pedir los precios de todo el resto. Finalmente cruzamos tu información con la nuestra para obtener un cálculo bastante aproximado del total de la obra.</p>
			<h4>Obra</h4>
			<p>Antes de comenzar debemos realizar todas las presentaciones legales pertinentes a los diferentes organismos (municipio, provincia, consorcio, servicios de luz, 
			gas, agua, etc.) Esta dependerá del tipo de obra que realicemos (obra nueva, remodelación, reforma, decoración) Una vez terminados estos trámites podemos empezar. 
			Nosotros aquí nos cargamos la obra al hombro y comenzamos. Podrás venir a la obra cuando quieras e ir verificando el avance de esta e ilusionándote a medida 
			que el proyecto se va haciendo realidad, día a día.
			Tendremos encuentros periódicos con 2 objetivos fundamentales:</p>
			<ul><li>Iremos juntos a comprar aquellos revestimientos, griferías y demás hermosos elementos que harán de tu casa un lugar único.</li>
			<li>Semanal, quincenal o mensualmente te rendiremos cuentas y deberás saldar lo que el avance de obra</li></ul>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
		</div>
	</div>

</div>