<div class="modal-dialog">

	<!-- Modal content-->
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title">Asesoramiento</h4>
		</div>
		<div class="modal-body">
			<h1>Ley 257 ?</h1>
<p>La Ley 257 de la Ciudad Autónoma de Buenos Aires establece las obligaciones del propietario
relativas a la conservación de su inmueble. El objetivo final del trámite es la obtención del
Certificado de Conservación. De acuerdo a la normativa vigente, todos los edificios, casas y PH,
deben mantener en buen estado de conservación de sus fachadas y sectores internos (huecos
de aire y luz). En donde sea posible el desprendimiento de elementos de mampostería,
estructurales, antenas, equipos de climatización, macetas, marquesinas, toldos, carteles, etc.,
que puedan ocasionar peligro para las personas o bienes.
 En qué consiste el trámite?
Elaboramos un Informe Técnico que se realiza a partir de la inspección visual de todos los
elementos descriptos, momento en el cual se toman muestras fotográficas, con el fin de
establecer la existencia o no de patologías. El Informe Técnico entonces, establece el estado de
prevención e integridad del inmueble.
A) Cuando el inmueble esté en buenas condiciones, se emitirá el Certificado de Conservación,
con una validez de acuerdo a la antigüedad del edificio, y que deberá renovarse una vez
vencido.
B) Si por el contrario presenta elementos deteriorados, se otorgará un plazo para efectuar las
reparaciones, vencido el cual se hará otra visita para constatar la situación y se realizará el
Certificado de Conservación en ese momento.
Que pasos seguimos para obtener el Certificado de Conservación :
A) Análisis del estado de frentes, contrafrentes, huecos de aire y luz y medianeras. Inspección,
relevamiento fotográfico.

B) Realización del Informe Técnico, firma del propietario y el arquitecto, presentación ante el
CPAU (Consejo de Profesionales de Arquitectura
y Urbanismo).
C) Entrega del Certificado de Conservación aprobado por la AGC (Agencia Gubernamental de
Control), dependencia del Gobierno
de la Ciudad.</p>
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
		</div>
	</div>

</div>