<div class="navbar-fixed-top">
	<div id="navbar" class="container-fluid">
		<div class="nav-img">
			<img alt="Brand" class="img-responsive" src="img/logo.png">
		</div>
		<div class="menu">
			<ul class="nav nav-pills">
				<li role="presentation"><a onclick="javascript:navBar('slide');">HOME</a></li>
				<li role="presentation"><a onclick="javascript:navBar('servicios');">SERVICIOS</a></li>
				<li role="presentation"><a onclick="javascript:navBar('footer');">QUIENES SOMOS</a></li>
				<li role="presentation"><a onclick="javascript:navBar('footer');">CONTACTO</a></li>
			</ul>
		</div>
		<div class="menu-mobile navbar-collapse collapse">
			<ul class="nav navbar-nav">
        		<li class="active"><a href="#">Home</a></li>
        		<li><a href="#">SERVICIOS</a></li>
        		<li><a href="#">QUIENES SOMOS</a></li>
        		<li><a href="#">CONTACTO</a></li>
        	</ul>
		</div>
	</div>
</div>