<div class="navbar navbar-default navbar-fixed-top navbar-custom">
 <div class="navbar-header">
      <a class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav nav-pills">
        <li><a onclick="javascript:navBar('slide');">HOME</a></li>
        <li><a onclick="javascript:navBar('servicios');">SERVICIOS</a></li>
        <li><a onclick="javascript:navBar('footer');">QUIENES SOMOS</a></li>
        <li><a onclick="javascript:navBar('footer');">CONTACTO</a></li>
      </ul>
    </div>
    <div class="nav-img margin-left-auto">
			<img alt="Brand" class="img-responsive" src="img/logo.jpg">
		</div>
</div>