<div id="slide" class="slideshow-container">
	<div class="mySlides fades">
		<div class="numbertext">1 / 3</div>
	 	<img src="img/slide1.jpg" class="img-responsive img-slide" style="width: 100%">
		<h1 class="titleSlide1">Arquitectura &amp;<br>Construcci&oacute;n </h1>
		<div class="text">Generamos m&eacute;todos de aproximaci&oacute;n a las necesidades del cliente,
		 mostrando con claridad cu&aacute;l ser&aacute; el camino a recorrer; haciendo de este un proceso sencillo por 
		 el cual el cliente no debe preocuparse ya que ser&aacute; acompa&ntilde;ado por profesionales que se encargar&aacute;n 
		 de cada una de las etapas hasta la conclusi&oacute;n definitiva del proyecto.
		 </div>
		 <input id="slideButton" type="button" onclick="javascript:openModal('myModal');" value="M&aacute;s informaci&oacute;n &raquo; ">
	</div>

	<div class="mySlides fades">
		<div class="numbertext">2 / 3</div>
		<img src="img/slide2.jpg" class="img-responsive img-slide" style="width: 100%">
		<h1 class="titleSlide2">Nuestra Misi&oacute;n: <br> &quot;Analizar, proponer, optimizar y construir&quot;</h1>
		<!--     <div class="text">Caption Two</div> -->
	</div>

	<div class="mySlides fades">
		<div class="numbertext">3 / 3</div>
		<img src="img/slide3.jpg" class="img-responsive" style="width: 100%">
		<h1 class="titleSlide1">Ley 257</h1>
		<div class="text3">La Ley 257 de la ciudad Aut&oacute;mana de Buenos AIres establece las obligaciones del propietario relativas
		a la conservaci&oacute;n de su inmueble. El objetivo final del tr&aacute;mite es la obtenci&oacute;n del Certificado de Conservaci&oacute;n.
		De acuerdo a la normativa vigente, todos los edificios, casas y PH, deben mantener en buen estado de conservaci&oacute;n sus fachadas
		y sectores internos (huecos de aire y luz). En donde sea posible el desprendimiento de elementos de mamposter&iacute;a, estructurales, antenas,
		 equipos de climatizaci&oacute;n, macetas, marquesinas, toldos, carteles, etc., que puedan ocasionar peligro para las personas o bienes.
		</div>
		 <input id="slideButton" type="button" onclick="javascript:openModal('modaLey');" value="¿En qu&eacute; consiste el tr&aacute;mite?">
	</div>

	<a class="prev" onclick="plusSlides(-1)">&#10094;</a> <a class="next"
		onclick="plusSlides(1)">&#10095;</a>
</div>

<div style="text-align: center">
	<span class="dot" onclick="currentSlide(1)"></span>
	<span class="dot" onclick="currentSlide(2)"></span>
	<span class="dot" onclick="currentSlide(3)"></span>
</div>


<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  var i;
  var slides = document.getElementsByClassName("mySlides");
  var dots = document.getElementsByClassName("dot");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  for (i = 0; i < dots.length; i++) {
      dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";  
  dots[slideIndex-1].className += " active";
}

</script>
